/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Camping1.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export const Camping1 = (props) => {
  const { nodes, materials } = useGLTF("models/Camping1.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.313, 0.636, -0.077]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <group position={[239.051, -410.517, -19.714]}>
          <mesh
            geometry={nodes.Trunk_1.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          />
          <mesh
            geometry={nodes.Trunk_1__1_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[344, 241, -4.3]}
          />
          <mesh
            geometry={nodes.Trunk_2.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-78.4, -96.3, 1.7]}
          />
          <mesh
            geometry={nodes.Trunk_3.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[183.785, -39, -24.93]}
          />
          <mesh
            geometry={nodes.Trunk_3__1_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[136.026, 5, -19.614]}
          />
          <mesh
            geometry={nodes.Trunk_4.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-212.413, -166, -7.6]}
          />
          <mesh
            geometry={nodes.Trunk_4__1_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-548, -13, -8.1]}
          />
          <mesh
            geometry={nodes.Trunk_4__2_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-384, 951, -3.4]}
          />
          <mesh
            geometry={nodes.Trunk_5.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[174, 850, -12]}
          />
          <mesh
            geometry={nodes.Trunk_5__1_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-478, 948, -8.1]}
          />
          <mesh
            geometry={nodes.Trunk_6.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-141, 421, -9]}
          />
          <mesh
            geometry={nodes.Trunk_7.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-181.24, 64.58, -1.28]}
          />
          <mesh
            geometry={nodes.Trunk_7__1_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-326, 299, -9.4]}
          />
          <mesh
            geometry={nodes.Trunk_7__2_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-352, 91, -14.5]}
          />
          <mesh
            geometry={nodes.Trunk_8.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-291.33, -23.3, -10.23]}
          />
          <mesh
            geometry={nodes.Trunk_8__1_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[279, 326, -6.6]}
          />
          <mesh
            geometry={nodes.Trunk_9.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[-185, 433, -8]}
          />
        </group>
        <group position={[42.355, 26.961, -29.069]}>
          <mesh
            geometry={nodes.Trunk_Wood_1.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[78.1, -79.6, -5.9]}
            rotation={[-0.002, -0.005, -0.408]}
          />
          <mesh
            geometry={nodes.Trunk_Wood_1__1_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[100.054, -443.414, -4.186]}
          />
          <mesh
            geometry={nodes.Trunk_Wood_1__2_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[120.353, -444.867, -3.705]}
          />
          <mesh
            geometry={nodes.Trunk_Wood_1__3_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[109.748, -445.859, -13.9]}
          />
          <mesh
            geometry={nodes.Trunk_Wood_1__4_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[89.91, -438.875, -14.077]}
          />
          <mesh
            geometry={nodes.Trunk_Wood_2.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[137.5, -450.3, -3.2]}
            rotation={[-3.099, -0.385, -3.006]}
          />
          <mesh
            geometry={nodes.Trunk_Wood_2__1_.geometry}
            material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
            position={[81.618, -450.32, -2.71]}
          />
        </group>
        <mesh
          geometry={nodes.Bear.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[422.947, 265.305, -68.317]}
        />
        <mesh
          geometry={nodes.Deer.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-209.725, -244.204, -66.654]}
        />
        <mesh
          geometry={nodes.Wolf.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-312.057, 240.935, -362.86]}
        />
        <mesh
          geometry={nodes.Axe_1.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-59.755, -427.218, -44.283]}
        />
        <mesh
          geometry={nodes.Floting_Base_1.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
        />
        <mesh
          geometry={nodes.Floting_Base_2.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[150.955, -144.302, -30.283]}
        />
        <mesh
          geometry={nodes.Car_1.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[430.702, -150.236, -56.67]}
        />
        <mesh
          geometry={nodes.Christmas_Tree_1.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[286.025, 463.315, -14.244]}
        />
        <mesh
          geometry={nodes.Christmas_Tree_2.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[198.213, 321.544, -25.303]}
        />
        <mesh
          geometry={nodes.Christmas_Tree_3.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[401.346, 341.569, -28.858]}
        />
        <mesh
          geometry={nodes.Fire_Wood___Stone_1.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[195.68, -40.003, -30.4]}
        />
        <mesh
          geometry={nodes.Grass_1.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[518.933, 324.747, -25.048]}
        />
        <mesh
          geometry={nodes.Grass_1__10_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[419.73, -257.898, -26.236]}
        />
        <mesh
          geometry={nodes.Grass_1__11_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[343.566, -29.011, -32.95]}
        />
        <mesh
          geometry={nodes.Grass_1__12_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[571.046, -146.572, -22.1]}
        />
        <mesh
          geometry={nodes.Grass_1__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[367.724, 427.896, -24.634]}
        />
        <mesh
          geometry={nodes.Grass_1__2_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[201.095, 468.427, -23.6]}
        />
        <mesh
          geometry={nodes.Grass_1__3_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-429.786, 114.124, -23.662]}
        />
        <mesh
          geometry={nodes.Grass_1__4_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-402.069, 10.652, -18.849]}
        />
        <mesh
          geometry={nodes.Grass_1__5_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-473.689, -258.303, -19.983]}
        />
        <mesh
          geometry={nodes.Grass_1__6_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-358.447, -275.286, -19.991]}
        />
        <mesh
          geometry={nodes.Grass_1__7_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-133.814, -404.761, -25.161]}
        />
        <mesh
          geometry={nodes.Grass_1__8_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-107.497, -432.745, -25.161]}
        />
        <mesh
          geometry={nodes.Grass_1__9_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[184.714, -405.756, -25.161]}
        />
        <mesh
          geometry={nodes.Grass_2.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[259.346, 204.726, -28.484]}
        />
        <mesh
          geometry={nodes.Grass_2__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-167.938, -284.014, -30.957]}
        />
        <mesh
          geometry={nodes.Grass_2__2_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[13.731, -495.143, -32.806]}
        />
        <mesh
          geometry={nodes.Grass_2__3_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[535.726, 48.069, -24.402]}
        />
        <mesh
          geometry={nodes.Grass_3.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[18.544, 221.684, -29.838]}
        />
        <mesh
          geometry={nodes.Grass_3__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-98.99, 378.046, -32.906]}
        />
        <mesh
          geometry={nodes.Grass_3__2_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-85.017, 511.1, -24.465]}
        />
        <mesh
          geometry={nodes.Grass_3__3_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-266.258, 539.813, -39.703]}
        />
        <mesh
          geometry={nodes.Grass_3__4_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-118.619, -144.082, -22.6]}
        />
        <mesh
          geometry={nodes.Grass_3__5_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[149.071, 18.308, -23.796]}
        />
        <mesh
          geometry={nodes.Grass_3__6_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[459.69, -103.592, -23.772]}
        />
        <mesh
          geometry={nodes.Big_Rock.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-292.423, 304.496, 75]}
        />
        <mesh
          geometry={nodes.Rock_1.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-153.095, 131.021, -17.026]}
        />
        <mesh
          geometry={nodes.Rock_1__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-189.968, 72.495, -28.016]}
          scale={0.496}
        />
        <mesh
          geometry={nodes.Rock_1__2_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[524.654, 5.867, -28.19]}
          scale={0.788}
        />
        <mesh
          geometry={nodes.Rock_1__3_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[186.298, -0.057, -27.619]}
          scale={0.496}
        />
        <mesh
          geometry={nodes.Rock_1__4_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-74.656, -506.393, -31.219]}
          scale={0.541}
        />
        <mesh
          geometry={nodes.Rock_2.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-38.263, -41.07, -37.508]}
        />
        <mesh
          geometry={nodes.Rock_2__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[337.03, 182.61, -29.699]}
        />
        <mesh
          geometry={nodes.Rock_2__2_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-31.495, -494.806, -37.581]}
          scale={1.044}
        />
        <mesh
          geometry={nodes.Rock_3.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[370.27, 192.465, -18.461]}
        />
        <mesh
          geometry={nodes.Rock_3__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-4.867, -8.035, -39.042]}
          scale={0.585}
        />
        <mesh
          geometry={nodes.Rock_4.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[462.381, 20.376, -25.408]}
        />
        <mesh
          geometry={nodes.Rock_4__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[240.213, 15.849, -17.658]}
        />
        <mesh
          geometry={nodes.Rock_4__2_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-391.938, -250.665, -26.289]}
        />
        <mesh
          geometry={nodes.Skeleton_1.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[18.558, 425.404, -31.565]}
        />
        <mesh
          geometry={nodes.Tant_1.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[231.387, -195.409, -56.96]}
        />
        <mesh
          geometry={nodes.Tant_2.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[99.582, -193.695, -53.309]}
        />
        <mesh
          geometry={nodes.Tree_1.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[525.443, -248.173, -25.433]}
        />
        <mesh
          geometry={nodes.Tree_11.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-181.283, -441.386, -26.371]}
        />
        <mesh
          geometry={nodes.Tree_11__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-346.106, 16.277, -25.471]}
        />
        <mesh
          geometry={nodes.Tree_1__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-346.744, -353.078, -25.433]}
        />
        <mesh
          geometry={nodes.Tree_2.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[498.505, -347.088, -24.782]}
        />
        <mesh
          geometry={nodes.Tree_2__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-293.857, -253.507, -24.782]}
        />
        <mesh
          geometry={nodes.Tree_3.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[524.475, -413.029, -24.024]}
        />
        <mesh
          geometry={nodes.Tree_3__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-81.651, 471.145, -23.574]}
        />
        <mesh
          geometry={nodes.Tree_4.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[400.005, -286.237, -22.344]}
        />
        <mesh
          geometry={nodes.Tree_4__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-441.133, -262.611, -22.6]}
        />
        <mesh
          geometry={nodes.Tree_5.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[416.428, -385.895, -23.594]}
        />
        <mesh
          geometry={nodes.Tree_5__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-457.267, -355.89, -15.87]}
        />
        <mesh
          geometry={nodes.Tree_6.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[445.648, -466.461, -21.09]}
        />
        <mesh
          geometry={nodes.Tree_6__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-500.561, -227.056, -21.09]}
        />
        <mesh
          geometry={nodes.Tree_7.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[337.366, -458.399, -28.096]}
        />
        <mesh
          geometry={nodes.Tree_7__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-219.019, -383.504, -28.096]}
        />
        <mesh
          geometry={nodes.Tree_8.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[341.91, -366.3, -28.112]}
        />
        <mesh
          geometry={nodes.Tree_9.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[251.737, -521.343, -24.039]}
        />
        <mesh
          geometry={nodes.Tree_9__1_.geometry}
          material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
          position={[-500, 79, -24.039]}
        />
      </group>
      <mesh
        geometry={nodes.Trunk_3_1.geometry}
        material={materials["Lowpoly_Flaoting_Islands_PortTexture.002"]}
        position={[0.757, 0.851, -5.387]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
};

useGLTF.preload("./models/Camping1.glb");
