/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CoffeePlant.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const CoffeePlant = (props) => {
  const { nodes, materials } = useGLTF("./models/CoffeePlant.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.CoffePlant_mehs.geometry}
        material={materials.CoffeePlant_mat}
      />
    </group>
  );
};
export default CoffeePlant;
useGLTF.preload("./models/CoffeePlant.glb");
